### ISSUE TITLE
ROS bulid failure

### ISSUE THREAD

**Issue by jgoppert** [PX4/PX4-SITL_gazebo-classic#112]
```bash
src/mavlink_sitl_gazebo/include/gazebo_geotagged_images_plugin.h:32:41: fatal error: mavlink/v2.0/common/mavlink.h: No such file or directory
```

Some include path issue, tracking it down now, wish we had CI on this.

**Comment by oceanusxiv** [comment]
I've also encountered this issue, however your fix didn't work, primarily I suspect because I am currently build mavros and mavlink from scratch. As such roscpp include dirs will not contain my mavros and mavlink installations. If Mavlink is to be removed from the repo I think a fix involving catkin would be far more versatile than just using cmake.

As a change, 
```cmake
find_package(mavlink)
if (mavlink_FOUND)
   include_directories(${mavlink_INCLUDE_DIRS})
endif()
```
is a much more specific command instead of the currently existing one if the goal is just to include mavlink from ROS

**Comment by canberkgurel** [comment]
The missing header file has been moved from `common` to `minimal`.
