### ISSUE TITLE
how to starting Gazebo and PX4 separately

### ISSUE THREAD

**Issue by TokyoClod** [PX4/PX4-SITL_gazebo-classic#113]
when i echo the code `make posix_sitl_default gazebo`,the virtual world and the default PX4 show together
i'm wondering how to starting Gazebo and PX4 separately,and modify the virtual world.
the code `make posix_sitl_default gazebo_none_ide`in PX4 Developer Guide doesn't work

**Comment by EliaTarasov** [comment]
You can run gazebo independently (but with all plugins that are needed to start copter model)
like this:
cd workspace/Firmware
export GAZEBO_PLUGIN_PATH=${GAZEBO_PLUGIN_PATH}:build/posix_sitl_default/build_gazebo
gazebo Tools/sitl_gazebo/worlds/iris.world --verbose

Then in separate window run: make posix_sitl_default gazebo no_sim=1

Now you have px4 and gazebo running separately

**Comment by hamishwillee** [comment]
@TokyoClod in what way do the instructions in  [PX4 Developer Guide > Gazebo](https://dev.px4.io/en/simulation/gazebo.html#start_px4_sim_separately) fail? These will need to be updated - see https://github.com/PX4/Devguide/issues/454
EDITED - ignore that. It fails because the target is no longer supported.

@EliaTarasov Thanks for that information. I can include it, but the existing material is centred around starting gazebo separately for debugging. Do you know how to do that (or can you just attach the IDE once you have started them separately as you indicated?)

**Comment by EliaTarasov** [comment]
Yes i usually just attach debugger (Eclipse in my case).

**Comment by cschindlbeck** [comment]
Can you be a little more verbose about the debugging process?

How can you attach a debugger in Eclipse?
Starting 
 `    make px4_sitl_default gazebo no_sim=1   `
in Eclipse shuts down immediately due to 
```
INFO  [px4] Startup script returned successfully
pxh> [2K
pxh> Shutting down
```


This is related to 
[https://discuss.px4.io/t/eclipse-debugging-sitl/9465](url)

**Comment by TSC21** [comment]
@cschindlbeck please do not necrobump old tasks. Open a new issue and describe your setup, what you are trying to do, the problem and what you already tried to fix it.
